js/app.js
아직 js초보인데 이번 미션에서는 함수를 최대한 분리하려고 노력했습니다. 
아직 부족한 점이 많으니 ㅠㅠ 많은 피드백 부탁드려요!
=> [박주한] TodoList CRUD

index.html, js/app.js, js/components/TodoApp.js, js/components/TodoCount.js, js/components/TodoInput.js, js/components/TodoList.js, js/components/TodoStatus.js, js/utils/constant.js, js/utils/localStorage.js
- todo list에 todoItem을 키보드로 입력하여 추가하기
- todo list의 체크박스를 클릭하여 complete 상태로 변경. (li tag 에 completed class 추가)
- todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
- todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기
- todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- 심화요구사항
더블클릭시 input모드로 변경 처리하는 것은 어떻게 해야할지 몰라서 구현하지 못했습니다.
=> [oceanide2] TodoList CRUD

index.html, src/App.js, src/Model.js, src/components/TodoList.js, src/index.js, src/util/index.js
미션 수행도 많이 늦었고 급하게하느라 완성도가 많이 떨어지네요ㅠㅠ 양해부탁드리겠습니다😭
=> [현석] 1주차 - TodoList CRUD

.gitignore, index.html
자바스크립트 만지는 건 거의 처음이라 
다른 분들 코드에 비해 한참 부족하네요. 그만큼 피드백 받을 것도 많습니다! 
많이 많이 지적해주십쇼!
=> [GraceLove] TodoList

index.html, src/TodoApp.js, src/TodoCount.js, src/TodoInput.js, src/TodoItem.js, src/TodoList.js, src/index.js
* 버그가 있다거나 개선 여지가 있는 부분 의견 부탁드립니다🙂
=> [read0more] TodoList CRUD

.prettierrc, .vscode/settings.json, components/App.js, components/TodoCount.js, components/TodoFilter.js, components/TodoInput.js, components/TodoList.js, index.html, index.js, utils/data.js, utils/util.js
Error 발생시 로그를 보여주는 부분을 아직 완성하지 못했습니다. TodoList 를 처음 개발했을 땐 함수들로만 구성해서 만들었는데 계속 진행하면서 컴포넌트 단위로 구성하고, pub-sub 패턴을 적용하는 등의 시도를 할 수 있었습니다! 기본을 강화하는데는 TodoList가 좋은 예제라는 생각이 듭니다.  
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Default_parameters
https://developer.mozilla.org/ko/docs/Web/API/Element/closest
=> [Sky] TodoList CRUD

index.html, js/TodoList.js, js/index.js
- todo list에 todoItem을 키보드로 입력하여 추가하기
- todo list의 체크박스를 클릭하여 complete 상태로 변경. (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
- todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
=> [Jess2] TODO 1주차 요구사항 구현

README.md, index.html, index.js, package-lock.json
✅ todo list에 todoItem을 키보드로 입력하여 추가하기<br>
✅ todo list의 체크박스를 클릭하여 complete 상태로 변경. (li tag 에 completed class 추가, input 태그에 checked 속성 추가).<br>
✅ todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제<br>
⬜ todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀<br>
✅ todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
⬜ todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기
✅ localStorage에 데이터를 저장하여, TodoItem의 CRUD를 반영하기. 따라서 새로고침하여도 저장된 데이터를 확인할 수 있어야 함
- todo list의 첫번째 항목만 line-through가 적용되고, x 버튼기능이 제대로 작동하는 문제점이 있습니다. 제 개인적인 생각으로는 querySelector로 해당 element를 부른 것이 문제라고 생각하는데요. 해당 부분에 대한 자료나 의견 주시면 감사하겠습니다.
- toggle 기능을 완수하지 못했습니다.
다른 분들의 코드를 통해 시야를 넓히는 유익한 시간이었습니다. 애자일 방법론에 대해 언급해주신 동준님 덕분에 아직 부족한 코드이지만 용기를 내 올려봅니다. 나머지 기능에 대해서는 스터디 자료 활용하여 더 …
=> [나현] TodoList CRUD 

index.html, js/Components/App.js, js/Components/TodoCount.js, js/Components/TodoFilter.js, js/Components/TodoInput.js, js/Components/TodoList.js, js/constants.js, js/index.js, js/todoLocalStorage.js, js/utils.js
- filter에서 event를 사용하지 않고 href # 을 사용한 이유와 해결 방법을 모르겠습니다 ㅠ
=> [lettuce] TodoList CRUD

TodoCount.js, TodoInput.js, TodoList.js, css/style.css, index.html, main.js, mission2/LICENSE, mission2/README.md, mission2/TodoCount.js, mission2/TodoInput.js, mission2/TodoList.js, mission2/Users.js, mission2/api.js, mission2/css/style.css, mission2/index.html, mission2/main.js
🎯 요구사항
* todo list에 todoItem을 키보드로 입력하여 추가하기
* todo list의 체크박스를 클릭하여 complete 상태로 변경. (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
* todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
* todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀 (x)
* todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
* todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기
---
질문사항
애초에 전체 데이터를 저장해서 어떤 것을 클릭하냐에 따라 다르게 보일 수 있도록 했는데 더 좋은 방식이 있는지 궁금합니다!!
인풋 데이터를 받으면 맨 아래에 있는 데이터의 체크박스 클릭이 안되는데 아무리 해봐도 잘 안됩니다 ㅠㅠ
=> [명지] TodoList CRUD

index.html, js/app.js
마지막 카운트, 탭 클릭에 따른 상태변화는 구현하지 못했습니다. ㅠㅠ
일이 한창 바쁜 시기와 스터디 시작이 맞물려서 시간 투자를 충분히 하지 못했네요;; ㅠㅠ
완성도 완성이지만 일단 PR을 열어보는 경험이 중요할 것 같아 일단 PR 오픈하겠습니다. 
열어놓고 나서도, 틈틈이 진행 사항 보충할게요. 감사합니다!
=> [wheejuni]todo list-CRUD

index.html, js/LocalStorageHelper.js, js/index.js
1주차 미션 우선 1차 리뷰요청입니다.
뭔가 여기서 공부하고 저기서 공부한 내용들이 짬뽕이되어 기능이 동작은하지만, 코드 가독성이 높지가 않습니다 ㅠ.. 
setState & render 개념은 리액트를 잠깐 공부할때 보긴했으나, 익숙치 않아 우선은 평소 하던 스타일대로 했습니다. 
많은 지도편달 부탁드립니다.
=> [3기 catsbi] TodoList with CRUD

index.html, js/script.js
=> [4기 노승재] TodoList

index.html, src/db.js, src/filter.js, src/index.js, src/newInput.js, src/store.js, src/todo.js, src/todos.js, src/utils.js
=> [4기 홍석훈] TodoList CRUD

App.js, components/TodoCount.js, components/TodoInput.js, components/TodoList.js, components/TodoStatus.js, index.html, utils/constantsKey.js, utils/handleData.js, utils/handleStorage.js
🎯 요구사항
-
🎯🎯 심화 요구사항
-
😃  코멘트
-
- 각 기능별로 컴포넌트를 분리, 최상위 App컴포넌트에서 state를 관리하고 데이터를 렌더링하는 방식으로 구현했습니다.
- 데이터의 인덱스를 배열 자체의 index로 잡았는데, 추후 todoList의 순번을 관리할 필요가 생기면 이 부분을 Date.now()로 구현해보면 좋을 것 같습니다. 이 밖에 더 좋은 아이디어와 가감없는 리뷰 남겨주시면 감사하겠습니다 :)
=> [4기 Vicky] TodoList CRUD

README.md, index.html, src/components/App.js, src/components/Filter.js, src/components/TodoItem.js, src/components/TodoList.js, src/index.js, src/store/todoStore.js, src/utils.js, src/utils/action.js, src/utils/createElement.js, src/utils/utils.js
=> [4기 younho9] TodoList with CRUD

App.js, components/TodoCount.js, components/TodoFilter.js, components/TodoInput.js, components/TodoList.js, components/utils/newId.js, index.html, index.js, package-lock.json
- 요구사항을 다 완료하진 못했는데 작업한데 까지 먼저 올리겠습니다.
하단의 필터버튼을 통해서 todo가 보여지게 하는 부분을 작업중인데 hash부분도 막히고 아직 방법을 찾지못했습니다. 
생각보단 잘 안되네요 ㅠㅠ 좀더 해봐야할거같습니다.
- ~~방금 발견한 에러인데, util에서 newId컴포넌트에서 아이디를 생성해주는 함수를 넣어 todo마다 고유의 아이디를 갖도록 해놨는데,
잘 작동되다가도 id찍히는걸 보면 갑자기 아이디가 중복되어 있기도 하네요.. 이에 따라서 todo상태도 뒤죽박죽으로 되고,~~
이 문제는 해결했는데 새로고침하면 새로 아이디가 발급돼서 그런거 같습니다!
혹시 아시는 분들은 조언 감사하겠습니다..!🙇‍♀
=> [4기 Sarah1446] TodoList with CRUD

index.html, todoList.js
=> [4기 my-u] TodoList with CRUD

index.html, js/components/app.js, js/components/list.js, js/components/task.js, js/main.js, js/render.js, js/test/Todo.test.js
=> [5기 Junho U] TodoList with CRUD 

index.html, index.js, js/TodoApp.js, js/TodoCount.js, js/TodoFilters.js, js/TodoInput.js, js/TodoItem.js, js/TodoList.js
심화는 시간이 없어 못했습니다;;;
다음번 미션때 이번 심화까지 할 수 있도록 노력해볼게요!
=> [5기 HeeSang] TodoList

index.html, js/main.js
안녕하세요^^
필터부분, localStorage 부분뺴고 우선 PR 보냅니다. 
모듈화전에 우선 기능구현을 해보려고 했습니다.
감사합니다 ㅎ.ㅎ
=> [5기 Jamieshin0201] TodoList with CRUD

index.html, js/toDo.js
=> [5기 이은결] TodoList with CRUD

index.html, index.js
=> [5기 이정섭] TodoList with CRUD

README.md, css/style.css, index.html, src/App.js, src/components/TodoCount.js, src/components/TodoFilters.js, src/components/TodoInput.js, src/components/TodoItem.js, src/components/TodoList.js, src/components/index.js, src/core/Component/index.js, src/enums/Filter.js, src/index.js, src/modules/index.js, src/modules/todo/index.js, src/modules/todo/reducer.js, src/redux/index.js, src/redux/redux.js, src/utils/Storage.js
안녕하세요~ 5기 참가자 김수정입니다.
좀 많이 늦은 ㅎㅎ; 1주차 과제를 제출합니다.
자유롭게 코멘트 혹은 코드리뷰 달아주시면 정말 감사드리겠습니다!
=> [5기 김수정] TodoList with CRUD

index.html, todoList.js
두 번째 참여인데 이전에 받았던 리뷰들을 참고하여 만드려고 노력하였지만 역시 어렵네요.. 
아직 많이 부족하지만 많은 피드백 부탁드립니다.
=> [6기 my_U] TodoList with CRUD

index.html, todo.js
- [ x ] todo list에 todoItem을 키보드로 입력하여 추가하기
- [ x ] todo list의 체크박스를 클릭하여 complete 상태로 변경. (li tag 에 completed class 추가, input 태그에 checked 속성 추가)
- [ x ] todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- [ x ]  todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- [ x ] todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
아직 상태관리에 대해 이해를 못해서 순수 javascript로만 작성하여 제출합니다!! 오늘내로 이해하게된다면 수정하겠습니다.
=> [7기 TaeBeomShin] TodoList CRUD

index.html, js/main.js
🚀 기본 요구사항
🚀🚀 심화 요구사항
-------------------------
✏️ 고민🙄
- 초반에 작업을 li에 템플릿을 직접 추가하는 방식으로 코드를 작성했는데 filter구현을 하는 항목에서는 기존에 구현한 방식을 수정해야 할 것 같다고 느꼈습니다. 상태관리와도 연관된 문제라고 생각했는데 감이 잘 잡히지 않아서 현재 구현한 범위까지 PR 보냅니다. 😅
- 자바스크립트가 익숙하지 않아서 기능이 동작하는 것에만 초점을 두고 구현했습니다. 기본적인 내용이 지켜지지 않은 부분이 많이 있을텐데 코멘트 남겨주시면 스터디 해서 반영하겠습니다. 🙂🙂
- 내일 스터디 모임을 하면서 아이디어를 얻을 수 있었으면 좋겠습니다.
=> [7기 Jay] TodoList CRUD

index.html, index.js
🚀 기본 요구사항
🚀🚀 심화 요구사항
----------------------------------------------------------------------------------------
- 자바스크립트 입문한지 얼마 안되어서 모르는 부분이 많아 상태관리와 같은 것은 하나도 적용하지 못했고 코드가 너무 초라하네요.. 부족한 부분에 대해 공부를 많이 해보고 싶습니다. 어떤 부분이 모자랐는지 코멘트 달아주시면 공부해서 보완하도록 하겠습니다!
=> [7기 이하늘] TodoList with CRUD

css/style.css, index.html, todo.js
=> Romanticcoder

.eslintrc, src/javascript/app.js, src/javascript/controller/controller.js, src/javascript/db.js, src/javascript/model/model.js, src/javascript/utils/constants.js, src/javascript/utils/querySelector.js, src/javascript/utils/utils.js, src/javascript/view/inputView.js, src/javascript/view/todoCountView.js, src/javascript/view/todoListView.js, src/javascript/view/view.js
안녕하세요 남상혁입니다.
MVC 패턴을 이용해서 구현해봤습니다. 기본적인 뼈대는 [TODO MVC](https://todomvc.com/examples/vanillajs/) 를 참고했습니다.
=> [8기 남상혁] TodoList with CRUD

index.html, src/js/main.js
안녕하세요 홍인용입니다.
다른분들이 올리신것 잠깐 봤는데 다들 능력자시네요 ㅎㅎ
저는 컴포넌트로 나눠서 하진 못했습니다ㅠ 
기능 구현만 완료하였습니다.ㅎㅎ;
배울게 참 많은것 같습니다! 피드백 많이주세요 :)
한가지 궁금한점이 있는데 많은 분들이 함수를 const 변수에 담아서 사용하시던데.. 어떤 이유가 있을까요?
🎯 요구사항
🎯🎯 심화 요구사항
=> [8기 홍인용] TodoList with CRUD

.eslintrc.json, .gitignore, .prettierrc, app.js, constant.js, index.html, package-lock.json, package.json
* 어제(4/13) 작성하였던 시점보다 개선점이 있어 다시 풀리퀘스트를 보내려 하던 중 임의로 close, reopen를 눌렀습니다. 양해 부탁드려요 ㅠ
---
안녕하세요 처음 인사 드립니다!
모델링 기법에 대해 익숙하진 않아, 하나의 객체 내에서 기능 별로 나누려 해보았습니다.
그러나 일부 기능은 아직 부족하여 조금 다듬는 작업이 필요합니다 ㅎㅎ!
코드에서 변수명이나 의미가 불분명한 부분도 많을 텐데, 해주고 싶은 말씀 있으시다면 언제든지 편하게 부탁드려요 :)
🎯 요구사항
🎯🎯 심화 요구사항
---
**오류 발생 상황**
- 더블클릭했을 때 input 모드로 변경되나,  최초 더블클릭한 작업만 가능합니다. 
- ex) 'a' 라는 todo를 더블 클릭함. -> 새로 고침하기 이전엔 다른 요소를 더블 클릭해도 편집 모드가 수행되지 않음.
- ~~아직 원인을 못 찾아 고치진 못했습니다 :(~~
- 찾았습니다. `dblclick`을 해야 하는데 `dbclick`으로 되어 있었네요.. (4/14)
=> [8기 강경만] TodoList with CRUD

index.html, src/js/Todo.js, src/js/eventListner.js, src/js/index.js
🎯 요구사항
🎯🎯 심화 요구사항
==============
리뷰 부탁드립니다
감사합니다 😁
=> [8기 bbbnam(변자룡)] TodoList with CRUD

index.html, src/App.js, src/components/TodoItem.js, src/js/index.js
리액트하다가 바닐라 자바스크립트 하려니 어버버 어버버 하게 되네요....
미숙한 부분이 많을 듯 싶습니다 ㅠ.ㅠ
잘 부탁드립니다
=> [8기 hzerok] TodoList with CRUD

README.md, index.html, src/todo_list.js, todo_list.js
구현 속도가 느려 미완성 상태이지만...그래도 올리겠습니다.
=> [8기 jessi68] todo list

index.html, src/js/index.js
안녕하세요! 
블랙커피 스터디 레벨 1 참가한 주재성입니다.
처음으로 js를 이용해 직접 코드를 짜보는 상황이어서 어떻게든 기능만 구현해보자는 생각으로 겨우겨우 완성은 했습니다...!
기본적인 것부터 하나하나 찾아보면서 구성해봤는데 간단한 문법에서 상태관리까지 아직 공부해야할 부분이 많이 보이네요😥
좋은 기회라는 생각을 갖고 올려주신 코드 많이 참고하면서 계속 도전하는 느낌으로 열심히 공부해보겠습니다!!
=> [8기 주재성] TodoList with CRUD

index.html, index.js
상태관리에 대한 공부가 많이 필요하겠구나 라고 느낀 미션이었습니다.
컴포넌트 별로 나눠서 진행하지는 못했고 기능 구현에 우선 초점을 두고 진행했습니다 ㅎㅎ
요구사항 중 마지막 항목(todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기)은 구현을 아직 하지 않은 상태입니다 :)
=> [8기 heejaykong] TodoList with CRUD

README.md, index.html, src/javascript/app.js, src/javascript/components/TodoApp.js, src/javascript/components/TodoCount.js, src/javascript/components/TodoFilter.js, src/javascript/components/TodoInput.js, src/javascript/components/TodoList.js, src/javascript/components/model/TodoItemModel.js
안녕하세요 이번에 블랙커피 레벨1에 참여하게 된 이혜원입니다.
아직 많이 부족하지만 공부해가며 구현해봤습니다 잘부탁드립니다 !
🎯 요구사항
🎯🎯 심화 요구사항
=> [9기 이혜원] TodoList with CRUD

.gitignore, index.html, src/js/App.js, src/js/TodoItem.js, src/js/component/TodoCount.js, src/js/component/TodoInput.js, src/js/component/TodoList.js, src/js/utils/utils.js
안녕하세요 박종수입니다.
부족하지만 열심히 구현해봤습니다.
=> [9기 박종수] TodoList with CRUD

.eslintrc, .gitignore, .idea/.gitignore, .idea/js-todo-list-step1.iml, .idea/modules.xml, .idea/vcs.xml, .idea/watcherTasks.xml, .prettierrc, index.html, package-lock.json, package.json, src/js/app.js, src/js/components/todoCount.js, src/js/components/todoHeader.js, src/js/components/todoInput.js, src/js/components/todoItem.js, src/js/components/todoList.js, src/js/constant/constant.js
안녕하세요!!
앞서 커밋하신분들의 코드를 살펴보니 제 코드가 많이 부족해보이네요 😪
많이 배워야겠다는 생각입니다!!
---
=> [9기 kmin-283] TodoList with CRUD

README.md, index.html, src/App.js, src/js/TodoCount.js, src/js/TodoInput.js, src/js/TodoItem.js, src/js/TodoList.js, src/js/TodoListFilter.js, src/js/WebStorage.js
쉽고 간단할 거라 생각했는데, javascript 트렌드에 맞게(?) 작성하는게 낯설어서 쉽지 않았어요. 
그래서 한번 만들었던 걸 공부하면서 다시 만들었습니다. 블랙커피 참여하길 잘했단 생각이예요! 😃 
많이 부족하니 가감없는 리뷰 부탁드리겠습니다 🙏🏻  
- [데모 사이트](https://baek.dev/js-todo-list-step1/)  
---
=> [9기 baekdev] TodoList with CRUD

README.md, index.html
[9기 zincoder] TodoList with CRUD
=> [9기 zincoder] TodoList with CRUD

README.md, index.html, src/App.js, src/components/TodoApp.js, src/components/TodoCount.js, src/components/TodoInput.js, src/components/TodoList.js, src/constants/constatns.js, src/css/style.css, src/store/filterState.js, src/store/todoState.js, src/utils/localStorage.js, src/utils/utils.js
안녕하세요. 이번에 블랙커피 레벨 1 스터디에 참가한 김승규 입니다.
아직 많이 부족하지만, 같이 성장합시다!
---
- [DEMO 사이트 - TODO LIST](https://kimseunggyu.github.io/js-todo-list-step1/index.html)
---
---
- 이번 프로젝트를 구현하면서 최대한 성질별?로 구현하고자 했는데, 역시 어렵네요! ㅎㅎ 시간이 부족해서 많은 고민하지 못한게 아쉽습니다. 다음 부터는 좀 더 시간을 많이 투자하도록 노력해야겠습니다.
- 2개의 상태(filter, todolist)를 이용하여 상태 부분을 처리하였는데, 원래의 목적은 상태가 변하면 자동으로 렌더링(_render()) 이 되게끔 구현하고자 했는데 그렇지 못한 점이 아쉽다. 후에 리팩토링하고자 한다. (옵저버 패턴으로 해야 할 거 같음.)
=> [9기 KIMSEUGGYU] TodoList with CRUD 

index.html, src/js/statusControl.js, src/js/todoList.js
안녕하세요 블랙커피 9기 참가자 이은지입니다.
성장할 수 있는 좋은 기회에 참여하게 되어 기쁩니다.
함께 성장해요!
=> [9기 이은지] TodoList with CRUD

index.html, src/js/todo.js
JS **완전 초짜**인 취준생입니다.
상태관리 개념도 너무 어렵고 아직 JS가 익숙치 않아서 기능 구현에만 초점을 두고 코드를 짜보았습니다. 
정말 많이 부족하지만 잘 봐주셨으면 좋겠습니다!
다른 분들 풀리퀘를 보니 리액트처럼 컴포넌트화해서 쓰셨더라구요.. 😱😱😱...
많이 배워서 발전해나가겠습니다!
---
=> [9기 lastcow9000] TodoList with CRUD

index.html, src/js/todo.js
- 21.05.31 : 1,2,3,4 완료
- 21.06.03 : 5완료
=> [9기 백성규] TodoList with CRUD
